### ISSUE TITLE
naptár kitöltése - csak kérdés

### ISSUE THREAD

**Issue by ighcsakvar** [ighcsakvar/esterhazyiskola#66]
Szeretném kérdezni, hogy
- a honlapon mennyi idő után jelenik meg egy naptárbejegyzés.
- ha belépek az ighcsakvar fiókba, akkor melyik naptárat töltsem ki, hogy megjelenjen a honlapon is.
Köszönöm szépen!

Ui.: frissítés után átírja a szöveget - mármint a Github. Nem az látható, amit beírtam

Elvileg már meg is jelent a szöveg a megfelelő helyen. Most már csak az érdekes, amit az utóiratban írtam. De most, hogy nem fordíttatom le magyarra a honlapot, nem írta át.

**Comment by parphis** [comment]
@ighcsakvar 
 1. A naptárból az adatok 10 percenként töltődnek le a weboldalra. Ez a folyamat a szerveren fut, ahol a weboldal is van. Most megnéztem, 10:10-kor volt a legutóbbi.
 2. Nem az ighcsakvar fiók van összekötve a weboldal naptárával, hanem létrehoztam egy külön, csak naptárat tartalmazó fiókot erre a célra: emuesemenyek@gmail.com (ttSixA4to2wo). Itt három naptár van: alsósok, felsősök, és egész iskola. Bármelyikbe lehet írni, az iskola weboldalán színkódokkal fog megjelenni a naptárban.

Az utóiratot nem értem:( Milyen szöveget ír át a github, és milyen frissítés után?

**Comment by ighcsakvar** [comment]
Köszönöm a gyors választ!

Közben én is próbálkoztam és az ighcsakvar alatt az egész iskola naptárához beírt szöveg megjelent a naptárban. De ez lehet azért, mert az ighcsakvar-ban is felvettem az 'Egész iskola' naptárát?

Az utóirat nem érdekes annyira, csak furcsa volt. Azt írtam be, hogy: "a honlapon mennyi idő után jelenik meg egy naptárbejegyzés", és ha az oldalt lefordíttattam magyarra, akkor az jelent meg, hogy: "a honlapon mennyi idő után lehet meg egy naptárbejegyzés".  De most kikapcsoltam a fordítást, így nem változott semmi.

**Comment by parphis** [comment]
Hát azt nem látom, mi van az ighcsakvar fiókban, de lehetséges összekötni különböző google naptárakat különböző fiókokkal, így az is lehet, hogy abból a fiókból most látod az emuesemenyek@ naptárjait is. Szóval, ha abba beleírsz, akkor az meg fog jelenni a weboldalon is.
Én egyébként nem látok az teszt-oldalon új naptárbejegyzést márciusra.
