### ISSUE TITLE
ENTER

### ISSUE THREAD

**Issue by ighcsakvar** [ighcsakvar/esterhazyiskola#73]
Hogyan tudok sort törni egy adott szövegen belül?
az iskolavezetes.csv-ben az "intézményvezető általános iskolai tanár" szövegben az intézményvezető után.

**Comment by parphis** [comment]
@ighcsakvar Ennek több módja is lehet. Hosszútávon a célravezető az lenne, ha az `intézményvezető` megnevezést külön mezőbe tennénk a CSV-ben, és akkor a sablon, ami létrehozza a külcsínyt, a megfelelő helyre, akár külön sorba tudná tenni, és ha kell, külön formázást tudnánk rátenni.
Rövidtávon azt lehet tenni, hogy a CSV-be a sortöréshez beírsz egy `<br/>` -t. Bár ezt nem teszteltem, de működnie kellene.

De most valami félrement, mert a munkatársak képei nem jelennek meg, helyette a CSV fájlok nevei látszódnak egy dobozban.

**Comment by parphis** [comment]
@ighcsakvar Kipróbáltam, igazam volt, ha beteszel egy `<br/>` -t a szövegbe, akkor abból sortörés lesz.

A hiba pedig azért volt, mert a lap beállításainál, ahol meg van adva, hogy melyik CSV fájlból dolgozzon a sablon, teljes elérési út volt beírva, de ott elég csak a csv fájl neve. Pl. `technikai.csv`, nem kell a `/usr/pages/...`

**Comment by ighcsakvar** [comment]
Köszönöm a választ! Én rontottam el valamit?

**Comment by ighcsakvar** [comment]
Még mindig rossz volt, de megtaláltam a fájlnevet elérési úttal. Kitöröltem az elérési utat és most jó. Bár nem értem, hogy került az oda, ha eddig nem volt ott, mert én nem emlékszem, hogy ide írtam volna bármit. A lényeg, hogy most jó.
