### ISSUE TITLE
Belső hivatkozás + beiratkozás + egyéb

### ISSUE THREAD

**Issue by ighcsakvar** [ighcsakvar/esterhazyiskola#74]
- [x] Létrehoztam az Iskolai életen belül egy Beiratkozás aloldalt, ahol le tudjuk írni a fontos tudnivalókat. Tettem rá egy hivatkozást, ami ugyanúgy működik, mint az E-KRÉTA/e-Ügyintézés. Viszont a másik linket, ami a Dokumentumok/Letölthető dokumentumok/iskolai/Beiratkozás oldalra mutatna, nem tudtam, hogyan szúrjam be. 

- [x] A megjelenő almenükben a Beiratkozás nagyon jobbra van, csak az eleje látszódik. Meg lehet azt csinálni, hogyha nagyon jobbra vagyunk akkor a következő menüpont balra jelenjen meg? Ezt most máshol is észrevettem, beszéljünk róla!

- [x] Korábban a Beiratkozás kint volt a kezdő oldalon a járdán. Tedd vissza, légy szíves és mutasson az Iskolai élet/Beiratkozás menüpontra.
- [x]  A Diákönkormányzat oldalán a második képet szeretnénk a bekezdés másik oldalára tenni. Ha nem túl bonyolult, akkor ezt is mutasd meg nyugodtan, hogy szöveget, képet hogyan tudok elhelyezgetni egy oldalon.
- [x] A Naptárban a sárga csíkban nehezen olvasható a fehér szöveg. Kérlek, állítsd át feketére úgy, ahogy a felső jelmagyarázat csíkban is van.
- [x] Nem fogalmaztam egyértelműen, ne haragudj érte, de a főoldalon a beiratkozást a Kiemelt események mellé szerettük volna. De talán a leírásod alapján meg tudom csinálni. Ha nem megy, szólok. Sikerült kitennem (bár végül mégsem tesszük ki), csak azt nem tudom, hogy minden felirat előtt volt-e kis függőleges vonal vagy csak az elején.
- [x] Az oldalak főcímeinek színét én meg tudom változtatni? Olyan bordó színt próbálnánk ki, mint az első ház tetején van. 
- [x] Létrehoztam az elérhetőségeken belül a fenntartó részét. Átmásoltam a csákvári iskola mindenét, kitörölgettem, ami nem kell és átírtam a koordinátákat a térképen. Majdnem jó, csak a térkép nem jelenik meg. Nézd meg, kérlek, mi a baj!
- [x] Iskolai élet/Munkatársak/Technikai dolgozók Schvanner Tiborné képének méretét igazítani a többi képhez. A felbontást megváltoztattam Oszoliné képe alapján, ezt feltöltöttem a szerverre, de nem történt változás.

**Comment by parphis** [comment]
@ighcsakvar 

A belső oldalakhoz linket úgy lehet adni, hogy az oldal _Haladó beállítások_ lapján van egy *Slug* nevű paraméter, és ezt kipipálva lehet adni az oldalnak egy egyedi URL végződést. Ebben a konkrét esetben _beiratkozasi-dokumentumok_ nevet adtam neki (szóközök ugyanis nem szerepelhetnek a linkelésben). És akkor ahol meg szeretnéd hivatkozni ott így`/dokumentumok/letoeltheto-dokumentumok/letoltheto-iskolai/beiratkozasi-dokumentumok` írod be. Kb. annyi, hogy megnyitod az oldalt, _amire_ hivatkozni szeretnél, és kimásolod a domain utáni részt a sima perjellel együtt.

Gondolom, hogy a beiratkozás oldalt a Csengetési rendből másoltad. Ha nem kellenek a képek meg a többi, akkor azokat nyugodtan törölgesd ki a _A Lap Médiái_ részből, hogy ne legyen feleslegesen duplikálódás.

Kitettem a linket a kezdőoldalra. Ezt egyébként a `Kezdőlap` nevű oldalon tudod módosítani. Itt egy HTML UL felsorolásba lehet tenni linkeket névvel, URL-lel.

A kicsúszott menü keményebb dió. Most már nem látok jól, és a szürkeállomány is elpihenne, de holnap délelőtt megnézem, mit lehet ott tenni.

**Comment by parphis** [comment]
#### A Diákönkormányzathoz

Jól csináltad a kép áthelyezését, igen. 

Röviden: Egy kép beszúrása ilyen módon lehetséges:

```
![](dok02.jpg?cropResize=200,200&classes=right)
```
 Ennek a részei pedig:
 1. A `!` mondja meg, hogy ez egy kép/pdf/videó, stb lesz.
 2. A `[ ]` közé kerül a link szövege. Ez kép esetében az a szöveg, ami akkor jelenik meg, amikor az egérmutatót a kép fölé visszük. Az `img` tag `alt` paraméterének nevezi a HTML szabvány.
 3. A `( )` közé kerül a kép elérési ótja, neve. Ez itt pl. a `dok02.jpg`. Az elérési út kiírására itt nincsen szükség, mivel a kép abban a mappában van, ahol az oldal maga is van.
 4. A fájlnév után állhatnak paraméterek, egy kérdőjellel elválasztva őket a fájl nevétől. Több paraméter is szerepelhet, ekkor őket az `&` jellel kell elválasztani egymástól. A példában a `cropResize=200,200` átméretezi a képet 200x200 pixel méretűvé, de úgy, hogy közben megtartja a képarányokat, tehát nem egy egyenlő oldaló négyszöget fogunk kapni. Ezen kívül az átméretezésnél esetleg keletkező üres részeklet is levágja. A második paraméter a `class=right` egy CSS osztályt ad a képhez. Ez itt elég beszédes, kitalálható, hogy a `right` pl. a szöveg jobb oldalához fogja rendezni a képet.

A [Grav CMS Media](https://learn.getgrav.org/16/content/media) elég jó, részletes leírással bír.

#### A Főoldali linkhez
A függőéleges vonal CSS-ből íródik hozzá a menüpontokhoz, ezzel a szövegben nem kell foglalkozni.

#### A menü színeihez
Igen, tudod te is módosítani természetesen. Van egy CSS fájl, amiben az eredeti oldal sablonhoz képesti stíluslapi-eltéréseket írjuk be: `public_html/parphis/user/themes/quark-open-publishing/css/custom.css`. Ebben fogsz találni egy `#header a` szelektort, benne egy `color` tulajdonságot, ami most `black`. Ide tudsz írni HTML színkódot is, pl. `#0DA6A2`, de a színek angol neveit is meg lehet adni, pl. `grey`, vagy `lightgreen`. Ebben nagy segítség tud lenni a fejlesztői konzol, ami minden böngészőhöz elérhető így vagy úgy. Ezt, ha gondolod, megmutatom személyesen. [color-picker](https://www.colorschemer.com/color-picker/)

**Comment by ighcsakvar** [comment]
Megtaláltam a #header a szelektort, átírtam garkred-re, de nem változott meg. Nézzük meg közösen!

**Comment by parphis** [comment]
Ok, szólj majd, hogy mikor lenne jó.

**Comment by ighcsakvar** [comment]
A szín megváltozott, csak nem az, amire Ibolya gondolt. Ibolya az oldalak főcímére gondolt nem a menük nevére (tegnap este nem vettem észre, hogy a menük színe megváltozott). Ezt most visszaállítom és szerintem tudom, hogy mire gondolt Ibolya és azt hol kell átállítani.

**Comment by ighcsakvar** [comment]
Most megpróbáltam átállítani a színt, de nem úgy kell, ahogy gondoltam. Szerintem valamilyen html kód kell, amit tudnom kellene, de sajnos nem tudom.

**Comment by parphis** [comment]
Felvettem a `centered-text` osztályhoz egy `color: darkred` színt, így most minden oldalon, ahol H3, vagy H4 címsor van, az sötét vörössel jelenik meg.
