### ISSUE TITLE
Találkozó

### ISSUE THREAD

**Issue by ighcsakvar** [ighcsakvar/esterhazyiskola#75]
Holnap délután jó neked valamikor? A pontos időt még nem tudjuk, mert várunk egy információt, de ha neked van favorizált időpontod, megpróbálunk igazodni mi is.

**Comment by parphis** [comment]
@ighcsakvar  Csak a mai napom sűrű, de holnap elvileg nincsen semmi, így tudok alkalmazkodni. Délelőtt az órák miatt kell itthon lennem, de déltől elérhető vagyok.

**Comment by ighcsakvar** [comment]
Ma 14 órára gondoltunk. Megfelelő neked?
Szerinted, ha ma tanítgatsz engem, akkor azt Zsolti is hallja vagy ő úgyis tudja mindezt, amiket én kérdezgetek és elég lesz a tényleges indításkor hívni a Zsoltit?

**Comment by parphis** [comment]
Én nem tudom, hogy ki, és mit tud:) Ezt a döntést rátok bíznám. Talán az lehet a jó irány, hogy annak tanítgassam első körben, akinek a feladata lesz a tartalomfeltöltés.

Egyébként jó nekem a két óra, elvileg mindennel készen leszek addigra.

**Comment by ighcsakvar** [comment]
ok, akkor kettőkor. Egyelőre akkor maradok én, mint tanuló, s majd később meglátjuk, ki csinálja a tartalomfeltöltést, Apropó tartalomfeltöltés. Korábban beszéltünk a jogosultságokról, erről is beszéljünk délután.
