### ISSUE TITLE
ikonok

### ISSUE THREAD

**Issue by ighcsakvar** [ighcsakvar/esterhazyiskola#76]
Ibolyának jutott az eszébe, hogy bizonyos ikonokat ki kell tenni a kezdőlapra, mert ez kötelező. Ezeket összegyűjtöttük és azt képzeltük, hogy a kezdőlapot kellene megnövelni úgy, hogy a kép maradjon látható úgy ahogy van és alatta lenne egy rész, ami nem látható egyből, csak ha legörgetjük az oldalt, és ott lennének.
![05_HATÁRTALANUL](https://user-images.githubusercontent.com/77481626/112615466-d0520300-8e22-11eb-93b3-264bd260fb21.jpg)
![01_Esterházy](https://user-images.githubusercontent.com/77481626/112615467-d0ea9980-8e22-11eb-8837-a4068f90d6f8.png)
![02_SZEKESFEHERVAR (TK](https://user-images.githubusercontent.com/77481626/112615469-d21bc680-8e22-11eb-9aa9-4e9773eb0158.jpg)
![03_Kréta](https://user-images.githubusercontent.com/77481626/112615471-d2b45d00-8e22-11eb-9252-dcd504b49ff1.png)
![04_ENERGIATUDATOS ISK](https://user-images.githubusercontent.com/77481626/112615472-d2b45d00-8e22-11eb-93ca-367bb21ec5c0.jpeg)

**Comment by parphis** [comment]
A baj az, hogy a kezdőoldalon a kép az háttérkép, tehát nem lehet görgetni. De megcsináltam úgy, hogy a járda alatt vannak a képek kicsiben, de viszonylag láthatóan, és így mindenféle képernyőméreten is megmaradt minden a helyén.
