### ISSUE TITLE
Mentés

### ISSUE THREAD

**Issue by ighcsakvar** [ighcsakvar/esterhazyiskola#81]
Szia! Sikerült lementened a régi honlapot? Én sajnos elfelejtettem, hogy mit kell mindenképpen átmásolni. Elég csak a public.html mappát?

**Comment by parphis** [comment]
Másolom a mappákat, már csak a jelenlegi teszt `parphis` van hátra.

Igen, elég a `public_html`-t lementeni. Nem baj, ha te is megcsinálod, mert jobb, ha több példány van belőle.

**Comment by ighcsakvar** [comment]
Total Commanderben meg tudom nyitni az ftp szervert? Próbáltam beállítani a Filezilla alapján, úgy láttam, hogy felismerte a felhasználónevet, kérte a jelszót és utána autorizációs hibával leállt.

**Comment by ighcsakvar** [comment]
A Filezillában mentem most és vannak sikertelenátvitelként jelölt fájlok, illetve néhány fájlnál azt jelzi, hogy ilyen már van, mit csináljon vele, pedig teljesen üres mappába másolom, nem értem, hogyan lehetséges ez, hogy már van belőle.
