### ISSUE TITLE
Hibás működés

### ISSUE THREAD

**Issue by ighcsakvar** [ighcsakvar/esterhazyiskola#89]
Szia!
A legtöbb pdf-nél ezt az oldalt adja ki a honlap:
![image](https://user-images.githubusercontent.com/77481626/114691352-dea38880-9d17-11eb-8a42-8451b5b4267e.png)
Nézd meg kérlek, mi lehet a baj!
Köszönöm szépen!
Péter

**Comment by parphis** [comment]
Nem volt jó az átírányítási link: hiányzott az elejéről a `/` jel, valamint a végéről a PDF fájl neve. Végignéztem mindet, és mindenhol javítottam is őket.

**Comment by ighcsakvar** [comment]
Köszönöm, hogy kijavítottad mindet.
Az jutott most eszembe, hogy ha lesz még ilyen egyszerű probléma, ahol ugyanazt kell több helyen javítani, akkor egy ilyen rövid leírással és az egyik helyen történő javítással meg tudnád mutatni nekem a javítást és utána a többi helyen megcsinálnám én, hogy minél kevesebbet kelljen neked foglalkozni a javításokkal és mellesleg én is tanulok egy kicsit.
