### ISSUE TITLE
Eltűnő menü

### ISSUE THREAD

**Issue by ighcsakvar** [ighcsakvar/esterhazyiskola#90]
Szia!
Csak a kezdőlapon jelentkezik a hiba, belső oldalakon nem.
Az 'Iskolai élet' menü pont illetve az almenüi eltűnnek, ha az egeret a főmenü alsó szélénél lejjebb húzom.
Egy kis videót megpróbálok csatolni a problémáról.

https://user-images.githubusercontent.com/77481626/114826326-a491bf80-9dc7-11eb-9a50-8eb2422aa9a4.mp4

Sajnos az egér nem látszódik a videón, de a menüpontok kék kijelölése lehet támpont.
Peti

**Comment by parphis** [comment]
@ighcsakvar  Megoldottam:)
