### ISSUE TITLE
Személyes talákozó

### ISSUE THREAD

**Issue by ighcsakvar** [ighcsakvar/esterhazyiskola#91]
Szia István!
Te is írtad és mi is gondoltunk arra, hogy személyesen is találkozzunk.
Nekünk a jövő hét csütörtök, április 22-e megfelelő lenne a szokásos módon, amikor végzel a munkáddal, tehát 16:00 és 16:30 között valamikor.
Várom a visszajelzésed!
Péter

**Comment by parphis** [comment]
@ighcsakvar Helló, nekem is jó lehet a csütörtök. Akkor bemegyek négy magasságában.
