### ISSUE TITLE
PDF nyitása menüből

### ISSUE THREAD

**Issue by parphis** [ighcsakvar/esterhazyiskola#95]
@ighcsakvar 

Két dolgot találtam.

 1. Az oldal nevében több szóköz is van, és ezt valahogy át kell hidalni az elérési utaknál. Az egyik módszer az URL escapelés, amikor pl. `%20` -al helyettesítjük a szóközöket. Ez csúnya, ennél jobb módszer, ha a `slug` tulajdonságot állítjuk be, ahogyan azt tettem is: 
![kép](https://user-images.githubusercontent.com/22575079/117173546-2b392b80-adcd-11eb-932a-072d28f67370.png)

 2. És a fájl nevében is van szóköz. Ezt viszont csak helyettesítő karakterekkel lehet megoldani, így az `Oldal átirányítása` résznél a fájlnevet átírtam így: `Nyilatkozat%20etika_hittan%20valasztas.pdf`De ezt nem kell megjegyezned, mert ha az oldal tartalmánál a csatolmány plusz jelére kattintva beszúrod azt a tartalomhoz, akkor ott a kerek zárójelek közötti részt kell csak kimásolnod. 
![kép](https://user-images.githubusercontent.com/22575079/117173983-95ea6700-adcd-11eb-9c61-2000fcd20af5.png)

**Comment by ighcsakvar** [comment]
Köszönöm szépen a gyors segítséget!
